CREATE TABLE IF NOT EXISTS posts (
  id TEXT PRIMARY KEY,
  title TEXT NOT NULL,
  excerpt TEXT NOT NULL DEFAULT '',
  content TEXT NOT NULL,
  category TEXT NOT NULL DEFAULT 'Research',
  author TEXT NOT NULL DEFAULT 'CIVICAVITA AB',
  author_role TEXT NOT NULL DEFAULT '',
  date TEXT NOT NULL,
  cover_emoji TEXT NOT NULL DEFAULT '📝',
  read_minutes INTEGER NOT NULL DEFAULT 1,
  tags TEXT NOT NULL DEFAULT '[]',
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_posts_date ON posts(date DESC);
