import { useState } from 'react';
import { useLanguage } from '../i18n/LanguageContext';
import { useScrollAnimation } from '../hooks/useScrollAnimation';
import { Sparkles, FileText, ScrollText, FlaskConical, Copy, Check, Wand2, Search, Loader2 } from 'lucide-react';
import MarkdownOutput from './MarkdownOutput';

type ToolId = 'policy' | 'grant' | 'abstract' | 'grantFinder';

function generatePolicyBrief(topic: string, country: string, audience: string): string {
  const t = topic || '[health topic]';
  const c = country || '[country/region]';
  const a = audience || 'Ministry of Health';
  return `# Policy Brief — ${t} in ${c}

**Prepared for:** ${a}
**Date:** ${new Date().toLocaleDateString()}
**Classification:** Evidence-to-policy

## 1. Key Message
${c} faces a growing burden from ${t}. Without coordinated policy action, preventable morbidity and mortality will continue to rise, placing unsustainable pressure on the health system and household finances.

## 2. Situation Analysis
- Current epidemiological evidence indicates rising prevalence of ${t} across urban and rural populations in ${c}.
- Health system capacity remains oriented toward acute care, with limited investment in prevention, early detection, or long-term follow-up.
- Social determinants — including poverty, education, gender, and displacement — amplify vulnerability to ${t}.

## 3. Policy Options
1. **Integrate ${t} into primary health care.** Use every patient contact for screening, brief intervention, and referral.
2. **Protect essential supply chains.** Ring-fence procurement of essential commodities and diagnostics for ${t}.
3. **Invest in community health workers.** Task-shift detection and follow-up to the community level.
4. **Establish a national registry.** Build routine data on ${t} to inform planning and accountability.

## 4. Expected Impact
Modelling suggests that full implementation could reduce ${t}-related mortality by 20–30% within five years, with cost savings for the health system in averted hospitalizations.

## 5. Recommended Actions for ${a}
- Convene a multi-sectoral technical working group within 60 days.
- Allocate protected budget lines in the next fiscal cycle.
- Commission a baseline study to enable impact evaluation.

---
*Generated by Civicavita AB AI Policy Brief Assistant. Review and adapt with national stakeholders before publication.*`;
}

function generateGrantProposal(idea: string, donor: string, budget: string): string {
  const i = idea || '[project idea]';
  const d = donor || '[donor agency]';
  const b = budget || 'USD 500,000';
  return `# Grant Proposal Outline — ${i}

**Submitted to:** ${d}
**Requested budget:** ${b}
**Duration:** 24 months

## 1. Title
Strengthening Community Resilience through ${i}

## 2. Summary (250 words)
This proposal seeks ${b} from ${d} to implement a 24-month program centered on ${i}. Building on lessons from WHO, UNICEF and UN Women fieldwork in fragile and post-crisis settings, the project will combine community mobilization, health system strengthening, and evidence generation to deliver measurable improvements in health outcomes for vulnerable populations.

## 3. Problem Statement
Communities affected by protracted crises experience overlapping vulnerabilities: disrupted services, weakened social protection, and elevated risk of disease. ${i} represents a strategic entry point to address these vulnerabilities with a sustainable, community-owned approach.

## 4. Goal & Objectives
- **Goal:** Improve health and protection outcomes for 50,000 vulnerable individuals.
- **Objective 1:** Strengthen primary health service delivery in 20 target districts.
- **Objective 2:** Mobilize and train 400 community health workers.
- **Objective 3:** Establish a multi-sectoral referral and protection system.
- **Objective 4:** Generate evidence to inform national policy and scale-up.

## 5. Logical Framework (excerpt)
| Level | Indicator | Target | Source |
|---|---|---|---|
| Impact | Reduction in disease burden | 25% | DHS / national survey |
| Outcome | % facilities offering integrated services | 80% | HMIS |
| Output | CHWs trained | 400 | Training registry |

## 6. Implementation Approach
- Phase 1 (M1–M4): Inception, stakeholder mapping, baseline.
- Phase 2 (M5–M18): Implementation, adaptive management.
- Phase 3 (M19–M24): Evaluation, policy engagement, handover.

## 7. Budget Summary
- Personnel: 45%
- Program activities: 35%
- M&E and research: 10%
- Administration & overhead: 10%

## 8. Risk Management
Key risks include access constraints, political instability, and supply chain disruption. Mitigation includes flexible implementation modalities, pre-positioned supplies, and strong community ownership.

---
*Generated by Civicavita AB AI Grant Assistant. Customize with organizational data, partnerships, and donor-specific requirements.*`;
}

function generateAbstract(topic: string, methods: string, findings: string): string {
  const t = topic || '[research topic]';
  const m = methods || 'mixed-methods';
  const f = findings || '[key findings]';
  return `# Structured Research Abstract

**Title:** ${t}: A ${m} Study from Fragile and Post-Crisis Settings

**Background:** Despite growing global attention to ${t}, evidence from fragile and post-crisis settings remains limited. This study addresses that gap by examining determinants, service delivery models, and policy implications in low-resource humanitarian contexts.

**Methods:** We employed a ${m} design combining quantitative analysis of routine health information system data with qualitative interviews of health workers, community leaders, and service users. Data were collected across multiple districts using standardized tools. Ethical approval was obtained, and informed consent was secured from all participants.

**Results:** ${f}. Health system responsiveness varied substantially across districts, with community health worker engagement emerging as the strongest predictor of positive outcomes. Gender, displacement status, and socioeconomic position were significant effect modifiers.

**Discussion:** Findings confirm that ${t} cannot be addressed through vertical programs alone. Integrated primary health care, supported by task-shifting and community mobilization, offers the most promising pathway to scale.

**Conclusion:** Policymakers and donors should prioritize investment in integrated, community-owned models to deliver measurable improvements in ${t}. Further research is needed to refine implementation modalities across diverse crisis contexts.

**Keywords:** ${t}, fragile states, humanitarian health, primary health care, community health workers.

---
*Generated by Civicavita AB AI Research Abstract Assistant. Review, validate, and cite primary sources before submission.*`;
}

export default function AITools() {
  const { t, lang } = useLanguage();
  const { ref, isVisible } = useScrollAnimation(0.05);
  const [activeTool, setActiveTool] = useState<ToolId>('policy');
  const [copied, setCopied] = useState(false);

  // Form states
  const [policy, setPolicy] = useState({ topic: '', country: '', audience: '' });
  const [grant, setGrant] = useState({ idea: '', donor: '', budget: '' });
  const [abs, setAbs] = useState({ topic: '', methods: '', findings: '' });
  const [finder, setFinder] = useState({ project: '', region: '', budget: '', sector: '' });

  const [output, setOutput] = useState('');
  const [loading, setLoading] = useState(false);
  const [usedAI, setUsedAI] = useState(false);

  const [aiUnavailable, setAiUnavailable] = useState(false);

  const tools: { id: ToolId; icon: React.ReactNode; title: string; desc: string }[] = [
    { id: 'policy', icon: <ScrollText className="w-5 h-5" />, title: t.ai.toolPolicy, desc: t.ai.toolPolicyDesc },
    { id: 'grant', icon: <FileText className="w-5 h-5" />, title: t.ai.toolGrant, desc: t.ai.toolGrantDesc },
    { id: 'abstract', icon: <FlaskConical className="w-5 h-5" />, title: t.ai.toolAbstract, desc: t.ai.toolAbstractDesc },
    { id: 'grantFinder', icon: <Search className="w-5 h-5" />, title: t.ai.toolFinder, desc: t.ai.toolFinderDesc },
  ];

  const handleGenerate = async () => {
    setLoading(true);
    setUsedAI(false);

    // Build template fallback first
    let fallback = '';
    let prompt = '';
    if (activeTool === 'policy') {
      fallback = generatePolicyBrief(policy.topic, policy.country, policy.audience);
      prompt = `You are a senior public health policy advisor with 20+ years at WHO and UNICEF. Write a rigorous evidence-to-policy brief on "${policy.topic}" in "${policy.country}", addressed to "${policy.audience}". Use Markdown. Include: Key Message, Situation Analysis (3 bullets), Policy Options (4 numbered), Expected Impact, Recommended Actions (3 bullets). Be specific and actionable. ~500 words.`;
    } else if (activeTool === 'grant') {
      fallback = generateGrantProposal(grant.idea, grant.donor, grant.budget);
      prompt = `You are a senior grants manager who has designed USD 10M+ proposals for UN Women and UNDP. Write a grant proposal outline for "${grant.idea}" to be submitted to "${grant.donor}" with budget "${grant.budget}". Use Markdown with these sections: Title, Summary (250 words), Problem Statement, Goal & Objectives (4), Logical Framework table (Level/Indicator/Target/Source), Implementation Phases, Budget Summary, Risk Management. Be concrete and donor-aligned.`;
    } else if (activeTool === 'abstract') {
      fallback = generateAbstract(abs.topic, abs.methods, abs.findings);
      prompt = `You are a peer-reviewed journal editor. Write a structured research abstract on "${abs.topic}" using ${abs.methods} with findings: ${abs.findings}. Use Markdown headers: Background, Methods, Results, Discussion, Conclusion, Keywords. Keep under 300 words total. Academic tone.`;
    } else {
      fallback = generateGrantFinderFallback(finder);
      prompt = `You are a humanitarian funding specialist. Given this project: "${finder.project}" in region "${finder.region}", sector "${finder.sector}", budget "${finder.budget}", recommend 5 specific real donor opportunities (foundations, UN agencies, bilateral donors, EU instruments) that actually fund this kind of work. For each give: Donor name, Specific funding window/program, Typical grant size, Eligibility notes, Application tip. Use Markdown with headers per donor. Be specific — name real programs.`;
    }

    try {
      const response = await fetch('/api/ai/generate', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ prompt, language: lang }) });
      const data = await response.json().catch(() => ({}));
      if (!response.ok) throw new Error(data.error || 'AI service unavailable');
      setOutput(data.output);
      setUsedAI(true);
      setAiUnavailable(false);
    } catch {
      setOutput(fallback);
      setUsedAI(false);
      setAiUnavailable(true);
    } finally { setLoading(false); }
  };

  const generateGrantFinderFallback = (f: typeof finder): string => {
    const project = f.project || '[your project]';
    const region = f.region || '[target region]';
    const sector = f.sector || 'Global Health';
    const budget = f.budget || 'USD 500,000';
    return `# Donor Opportunities for: ${project}

**Region:** ${region} · **Sector:** ${sector} · **Budget:** ${budget}

## 1. UN Women — Peace and Humanitarian Action Window
- **Typical grant:** USD 200K – 2M
- **Eligibility:** NGOs/CSOs with demonstrated gender expertise
- **Tip:** Align with EVAW and Women, Peace & Security agenda

## 2. ECHO (European Civil Protection and Humanitarian Aid)
- **Typical grant:** EUR 500K – 5M
- **Eligibility:** International NGOs with field presence
- **Tip:** Use HIP (Humanitarian Implementation Plan) country priorities

## 3. Gates Foundation — Global Health Division
- **Typical grant:** USD 100K – 10M
- **Eligibility:** Research institutes, NGOs with evidence-based proposals
- **Tip:** Emphasize measurable outcomes and scale potential

## 4. USAID / BHA (Bureau for Humanitarian Assistance)
- **Typical grant:** USD 1M – 20M
- **Eligibility:** Established NGOs with DUNS number and SAM registration
- **Tip:** Follow Annual Program Statement (APS) guidelines

## 5. Global Fund to Fight AIDS, TB and Malaria
- **Typical grant:** Country-level multi-million
- **Eligibility:** Principal Recipients via Country Coordinating Mechanism
- **Tip:** Partner with Ministry of Health for submission

---
*Configure an OpenRouter API key in Admin → Settings for AI-powered, context-aware donor matching using live models.*`;
  };

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(output);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch { /* ignore */ }
  };

  return (
    <div className="relative min-h-screen pt-28 pb-20">
      <div className="absolute inset-0 bg-corp-900" />
      <div className="absolute top-0 right-0 w-[500px] h-[500px] bg-primary-500/5 rounded-full blur-[120px]" />
      <div className="absolute bottom-0 left-0 w-[400px] h-[400px] bg-violet-500/5 rounded-full blur-[100px]" />

      <div ref={ref} className="relative z-10 max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        {/* Header */}
        <div className={`text-center mb-12 transition-all duration-1000 ${isVisible ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-8'}`}>
          <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full glass-light mb-6">
            <Sparkles className="w-4 h-4 text-primary-400" />
            <span className="text-sm font-medium text-primary-400">{t.ai.badge}</span>
          </div>
          <h1 className="text-4xl sm:text-5xl lg:text-6xl font-display font-bold text-white tracking-tight mb-6">
            {t.ai.titlePart1}<span className="gradient-text">{t.ai.titleHighlight}</span>
          </h1>
          <p className="text-lg text-gray-400 max-w-2xl mx-auto">{t.ai.subtitle}</p>
          <p className="text-xs text-gray-500 mt-4 max-w-xl mx-auto">{t.ai.disclaimer}</p>
        </div>

        {/* Status bar */}
        <div className="mb-4 flex flex-wrap items-center justify-center gap-3 text-xs">
          <div className={`inline-flex items-center gap-1.5 px-3 py-1.5 rounded-full ${aiUnavailable ? 'bg-amber-500/15 text-amber-400 border border-amber-500/30' : 'bg-green-500/15 text-green-400 border border-green-500/30'}`}>
            <span className={`w-1.5 h-1.5 rounded-full ${aiUnavailable ? 'bg-amber-400' : 'bg-green-400'} animate-pulse`} />
            {aiUnavailable ? t.ai.aiStatusOff : t.ai.aiStatusOn}
          </div>
        </div>

        {/* Tool tabs */}
        <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-4 mb-8">
          {tools.map((tool) => (
            <button
              key={tool.id}
              onClick={() => { setActiveTool(tool.id); setOutput(''); }}
              className={`p-5 rounded-2xl text-start transition-all ${
                activeTool === tool.id
                  ? 'bg-gradient-to-br from-primary-500/20 to-primary-600/10 border-2 border-primary-500/40 shadow-lg shadow-primary-500/10'
                  : 'glass border-2 border-transparent hover:border-white/10'
              }`}
            >
              <div className={`w-10 h-10 rounded-xl flex items-center justify-center mb-3 ${activeTool === tool.id ? 'bg-primary-500/20 text-primary-400' : 'bg-white/5 text-gray-400'}`}>
                {tool.icon}
              </div>
              <h3 className="font-bold text-white mb-1">{tool.title}</h3>
              <p className="text-xs text-gray-400 leading-relaxed">{tool.desc}</p>
            </button>
          ))}
        </div>

        {/* Tool form + output */}
        <div className="grid lg:grid-cols-2 gap-6">
          {/* Form */}
          <div className="p-6 sm:p-8 rounded-2xl glass">
            <h3 className="text-xl font-bold text-white mb-5 flex items-center gap-2">
              <Wand2 className="w-5 h-5 text-primary-400" />
              {t.ai.inputHeading}
            </h3>

            {activeTool === 'policy' && (
              <div className="space-y-4">
                <div>
                  <label className="block text-sm font-medium text-gray-300 mb-2">{t.ai.fieldTopic}</label>
                  <input value={policy.topic} onChange={(e) => setPolicy({ ...policy, topic: e.target.value })} placeholder={t.ai.exampleTopic} className="w-full px-4 py-2.5 rounded-xl bg-white/5 border border-white/10 text-white placeholder-gray-500 focus:outline-none focus:ring-2 focus:ring-primary-500/50" />
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-300 mb-2">{t.ai.fieldCountry}</label>
                  <input value={policy.country} onChange={(e) => setPolicy({ ...policy, country: e.target.value })} placeholder={t.ai.exampleCountry} className="w-full px-4 py-2.5 rounded-xl bg-white/5 border border-white/10 text-white placeholder-gray-500 focus:outline-none focus:ring-2 focus:ring-primary-500/50" />
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-300 mb-2">{t.ai.fieldAudience}</label>
                  <input value={policy.audience} onChange={(e) => setPolicy({ ...policy, audience: e.target.value })} placeholder={t.ai.exampleAudience} className="w-full px-4 py-2.5 rounded-xl bg-white/5 border border-white/10 text-white placeholder-gray-500 focus:outline-none focus:ring-2 focus:ring-primary-500/50" />
                </div>
              </div>
            )}

            {activeTool === 'grant' && (
              <div className="space-y-4">
                <div>
                  <label className="block text-sm font-medium text-gray-300 mb-2">{t.ai.fieldIdea}</label>
                  <textarea rows={3} value={grant.idea} onChange={(e) => setGrant({ ...grant, idea: e.target.value })} placeholder={t.ai.exampleIdea} className="w-full px-4 py-2.5 rounded-xl bg-white/5 border border-white/10 text-white placeholder-gray-500 focus:outline-none focus:ring-2 focus:ring-primary-500/50 resize-none" />
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-300 mb-2">{t.ai.fieldDonor}</label>
                  <input value={grant.donor} onChange={(e) => setGrant({ ...grant, donor: e.target.value })} placeholder={t.ai.exampleDonor} className="w-full px-4 py-2.5 rounded-xl bg-white/5 border border-white/10 text-white placeholder-gray-500 focus:outline-none focus:ring-2 focus:ring-primary-500/50" />
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-300 mb-2">{t.ai.fieldBudget}</label>
                  <input value={grant.budget} onChange={(e) => setGrant({ ...grant, budget: e.target.value })} placeholder={t.ai.exampleBudget} className="w-full px-4 py-2.5 rounded-xl bg-white/5 border border-white/10 text-white placeholder-gray-500 focus:outline-none focus:ring-2 focus:ring-primary-500/50" />
                </div>
              </div>
            )}

            {activeTool === 'abstract' && (
              <div className="space-y-4">
                <div>
                  <label className="block text-sm font-medium text-gray-300 mb-2">{t.ai.fieldResearchTopic}</label>
                  <input value={abs.topic} onChange={(e) => setAbs({ ...abs, topic: e.target.value })} placeholder={t.ai.exampleResearchTopic} className="w-full px-4 py-2.5 rounded-xl bg-white/5 border border-white/10 text-white placeholder-gray-500 focus:outline-none focus:ring-2 focus:ring-primary-500/50" />
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-300 mb-2">{t.ai.fieldMethods}</label>
                  <input value={abs.methods} onChange={(e) => setAbs({ ...abs, methods: e.target.value })} placeholder={t.ai.exampleMethods} className="w-full px-4 py-2.5 rounded-xl bg-white/5 border border-white/10 text-white placeholder-gray-500 focus:outline-none focus:ring-2 focus:ring-primary-500/50" />
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-300 mb-2">{t.ai.fieldFindings}</label>
                  <textarea rows={3} value={abs.findings} onChange={(e) => setAbs({ ...abs, findings: e.target.value })} placeholder={t.ai.exampleFindings} className="w-full px-4 py-2.5 rounded-xl bg-white/5 border border-white/10 text-white placeholder-gray-500 focus:outline-none focus:ring-2 focus:ring-primary-500/50 resize-none" />
                </div>
              </div>
            )}

            {activeTool === 'grantFinder' && (
              <div className="space-y-4">
                <div>
                  <label className="block text-sm font-medium text-gray-300 mb-2">{t.ai.fieldProject}</label>
                  <textarea rows={2} value={finder.project} onChange={(e) => setFinder({ ...finder, project: e.target.value })} placeholder={t.ai.exampleProject} className="w-full px-4 py-2.5 rounded-xl bg-white/5 border border-white/10 text-white placeholder-gray-500 focus:outline-none focus:ring-2 focus:ring-primary-500/50 resize-none" />
                </div>
                <div className="grid grid-cols-2 gap-3">
                  <div>
                    <label className="block text-sm font-medium text-gray-300 mb-2">{t.ai.fieldRegion}</label>
                    <input value={finder.region} onChange={(e) => setFinder({ ...finder, region: e.target.value })} placeholder={t.ai.exampleRegion} className="w-full px-4 py-2.5 rounded-xl bg-white/5 border border-white/10 text-white placeholder-gray-500 focus:outline-none focus:ring-2 focus:ring-primary-500/50" />
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-gray-300 mb-2">{t.ai.fieldSector}</label>
                    <input value={finder.sector} onChange={(e) => setFinder({ ...finder, sector: e.target.value })} placeholder={t.ai.exampleSector} className="w-full px-4 py-2.5 rounded-xl bg-white/5 border border-white/10 text-white placeholder-gray-500 focus:outline-none focus:ring-2 focus:ring-primary-500/50" />
                  </div>
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-300 mb-2">{t.ai.fieldBudget}</label>
                  <input value={finder.budget} onChange={(e) => setFinder({ ...finder, budget: e.target.value })} placeholder={t.ai.exampleBudget} className="w-full px-4 py-2.5 rounded-xl bg-white/5 border border-white/10 text-white placeholder-gray-500 focus:outline-none focus:ring-2 focus:ring-primary-500/50" />
                </div>
              </div>
            )}

            <button
              onClick={handleGenerate}
              disabled={loading}
              className="mt-6 w-full px-6 py-3 bg-gradient-to-r from-primary-500 to-primary-600 hover:from-primary-400 hover:to-primary-500 text-white font-semibold rounded-xl shadow-lg shadow-primary-500/25 hover:shadow-primary-500/40 transition-all hover:-translate-y-0.5 flex items-center justify-center gap-2 disabled:opacity-50 disabled:hover:translate-y-0"
            >
              {loading ? <Loader2 className="w-4 h-4 animate-spin" /> : <Sparkles className="w-4 h-4" />}
              {loading ? t.ai.generating : t.ai.generate}
            </button>
          </div>

          {/* Output */}
          <div className="p-6 sm:p-8 rounded-2xl glass flex flex-col">
            <div className="flex items-center justify-between mb-4 flex-wrap gap-2">
              <h3 className="text-xl font-bold text-white flex items-center gap-2">
                {t.ai.outputHeading}
                {output && (
                  <span className={`text-[10px] px-2 py-0.5 rounded-full font-semibold uppercase tracking-wider ${usedAI ? 'bg-gradient-to-r from-blue-500/20 to-violet-500/20 text-blue-300 border border-blue-500/30' : 'bg-gray-500/20 text-gray-400 border border-gray-500/30'}`}>
                    {usedAI ? `✨ ${t.ai.aiBadge}` : t.ai.templateBadge}
                  </span>
                )}
              </h3>
              {output && (
                <button onClick={handleCopy} className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg glass-light hover:bg-white/10 text-gray-300 text-sm transition-colors">
                  {copied ? <Check className="w-4 h-4 text-primary-400" /> : <Copy className="w-4 h-4" />}
                  {copied ? t.ai.copied : t.ai.copy}
                </button>
              )}
            </div>
            <div className="flex-1 rounded-xl bg-corp-900/60 border border-white/5 p-5 overflow-auto max-h-[600px]">
              {loading ? (
                <div className="text-center py-16 text-gray-400">
                  <Loader2 className="w-10 h-10 mx-auto mb-3 animate-spin text-primary-400" />
                  <p className="text-sm">{t.ai.aiThinking}</p>
                </div>
              ) : output ? (
                <MarkdownOutput content={output} />
              ) : (
                <div className="text-center py-16 text-gray-500">
                  <Wand2 className="w-10 h-10 mx-auto mb-3 opacity-50" />
                  <p className="text-sm">{t.ai.emptyOutput}</p>
                </div>
              )}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
