import { ArrowRight, Sparkles } from 'lucide-react';
import { useScrollAnimation } from '../hooks/useScrollAnimation';
import { useLanguage } from '../i18n/LanguageContext';
const copy={
 en:{tag:'RESEARCH · STRATEGY · RESPONSIBLE AI',title:'Let’s build meaningful health solutions.',body:'Start a conversation about research, policy, knowledge systems or responsible AI for global health.',primary:'Start a conversation',secondary:'Read our insights'},
 fa:{tag:'پژوهش · راهبرد · هوش مصنوعی مسئولانه',title:'برای راه‌حل‌های معنادار سلامت، همراه شویم.',body:'برای گفتگو درباره پژوهش، سیاست‌گذاری، نظام‌های دانش یا هوش مصنوعی مسئولانه در سلامت جهانی با ما در تماس باشید.',primary:'شروع گفتگو',secondary:'مطالعه یادداشت‌ها'},
 sv:{tag:'FORSKNING · STRATEGI · ANSVARSFULL AI',title:'Låt oss skapa meningsfulla hälsolösningar.',body:'Inled ett samtal om forskning, policy, kunskapssystem eller ansvarsfull AI för global hälsa.',primary:'Inled ett samtal',secondary:'Läs våra insikter'},
 fr:{tag:'RECHERCHE · STRATÉGIE · IA RESPONSABLE',title:'Construisons des solutions de santé utiles.',body:'Échangeons sur la recherche, les politiques, les systèmes de connaissance ou l’IA responsable pour la santé mondiale.',primary:'Échanger avec nous',secondary:'Lire nos analyses'},
 ar:{tag:'البحث · الاستراتيجية · الذكاء الاصطناعي المسؤول',title:'لنبنِ حلولًا صحية ذات معنى.',body:'ابدأوا حوارًا حول البحث أو السياسات أو أنظمة المعرفة أو الذكاء الاصطناعي المسؤول للصحة العالمية.',primary:'ابدأ الحوار',secondary:'اقرأ الرؤى'}
} as const;
export default function CTABanner(){const {ref,isVisible}=useScrollAnimation(.1);const {lang}=useLanguage();const c=copy[lang];return <section className="relative py-24 sm:py-32 overflow-hidden"><div className="absolute inset-0 bg-gradient-to-br from-primary-900/80 via-corp-800 to-corp-900"/><div className="absolute inset-0 bg-[radial-gradient(ellipse_at_top_right,rgba(249,115,22,.13),transparent_60%)]"/><div ref={ref} className={`relative z-10 max-w-5xl mx-auto px-5 sm:px-8 text-center transition-all duration-700 ${isVisible?'opacity-100 translate-y-0':'opacity-0 translate-y-6'}`}><p className="text-xs text-primary-300 font-bold tracking-[.18em]">{c.tag}</p><Sparkles className="w-7 h-7 text-orange-400 mx-auto mt-6"/><h2 className="mt-6 text-4xl sm:text-5xl lg:text-6xl font-display font-bold text-white tracking-tight">{c.title}</h2><p className="mt-6 text-lg sm:text-xl text-gray-300 max-w-2xl mx-auto">{c.body}</p><div className="mt-10 flex flex-col sm:flex-row gap-4 justify-center"><a href="#contact" className="inline-flex gap-2 items-center justify-center px-8 py-4 bg-white text-corp-900 font-bold rounded-full">{c.primary}<ArrowRight className="w-5 h-5 rtl:rotate-180"/></a><a href="#insights" className="px-8 py-4 glass-light text-white font-semibold rounded-full border border-white/20">{c.secondary}</a></div></div></section>}
